<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Debit value</name>
  <uuid>74dcb9a6-c1e7-4868-81d8-f9ec86182d4e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the vr tot divida of cliente ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
