<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>1853e944-06bd-4df9-b5b0-8afd210a9951</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set taxa_juros_1 to 0.2 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
