<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>mapping</name>
  <uuid>9006e7ef-a322-4816-9158-54cad724bb00</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the ds grupo modalidade is the ds grupo modalidade of 'Input', 
		the escore is the escore of 'Input' , 
		the estado civil is the estado civil of 'Input' , 
		the genero is the genero of 'Input', 
		the idade is the idade of 'Input' , 
		the lime contratado is the lime contratado of 'Input' , 
		the lp mora is the lp mora of 'Input', 
		the nr dias atr is the nr dias atr of 'Input' , 
		the possui cartao is the possui cartao of 'Input', 
		the renda inferida is the renda inferida of 'Input' , 
		the status cliente is the status cliente of 'Input', 
		the status conta is the status conta of 'Input', 
		the tempo conta is the tempo conta of 'Input', 
		the vl cobranca is the vl cobranca of 'Input', 
		the vl liquido is the vl liquido of 'Input', 
		the vr entrada is the vr entrada of 'Input', 
		the vr parc reng is the vr parc reng of 'Input', 
		the vr renegociado is the vr renegociado of 'Input', 
		the vr tot divida is the vr tot divida of 'Input';]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
