<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Decision Output </name>
  <uuid>8ab43967-a55f-438d-9954-dbc230968883</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Taxa de juros do cliente: " + round(taxa_juros * 100,0) + "%" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
