<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output2</name>
  <uuid>198ecc14-6182-4da0-97e1-a092d85dd5d8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the prediction of 'ML model invocation' is 2
then
	set decision to "Cliente classe 2" ;
    print decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
