<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Predictive model output</name>
  <uuid>7d59daa7-09b0-40c5-827e-f7f9be6bfaf7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the predective modal computed from
		Input being cliente ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
